### ISSUE TITLE
error for android 4.4

### ISSUE THREAD

**Issue by m1faridi** [zladnrms/RoundableLayout#2]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 7930
    java.lang.NoClassDefFoundError: com.tistory.zladnrms.roundablelayout.RoundableLayout$a
        at com.tistory.zladnrms.roundablelayout.RoundableLayout.getOutlineProvider(:262)
        at com.tistory.zladnrms.roundablelayout.RoundableLayout.dispatchDraw(:223)
        at android.view.View.getDisplayList(View.java:13357)
        at android.view.View.getDisplayList(View.java:13404)
        at android.view.View.draw(View.java:14182)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.getDisplayList(View.java:13357)
        at android.view.View.getDisplayList(View.java:13404)
        at android.view.View.draw(View.java:14182)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at androidx.recyclerview.widget.RecyclerView.drawChild(:5204)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.draw(View.java:14468)
        at androidx.recyclerview.widget.RecyclerView.draw(:4603)
        at android.view.View.getDisplayList(View.java:13362)
        at android.view.View.getDisplayList(View.java:13404)
        at android.view.View.draw(View.java:14182)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.draw(View.java:14468)
        at android.view.View.getDisplayList(View.java:13362)
        at android.view.View.getDisplayList(View.java:13404)
        at android.view.View.draw(View.java:14182)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.draw(View.java:14468)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at androidx.core.widget.NestedScrollView.draw(:2073)
        at android.view.View.getDisplayList(View.java:13362)
        at android.view.View.getDisplayList(View.java:13404)
        at android.view.View.draw(View.java:14182)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.getDisplayList(View.java:13357)
        at android.view.View.getDisplayList(View.java:13404)
        at android.view.View.draw(View.java:14182)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.getDisplayList(View.java:13357)
        at android.view.View.getDisplayList(View.java:13404)
        at android.view.View.draw(View.java:14182)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at androidx.fragment.app.FragmentContainerView.drawChild(:268)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at androidx.fragment.app.FragmentContainerView.dispatchDraw(:256)
        at android.view.View.getDisplayList(View.java:13357)
        at android.view.View.getDisplayList(View.java:13404)
        at android.view.View.draw(View.java:14182)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(:1994)
        at android.view.View.getDisplayList(View.java:13357)
        at android.view.View.getDisplayList(View.java:13404)
        at android.view.View.draw(View.java:14182)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.draw(View.java:14468)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at android.view.View.getDisplayList(View.java:13362)
        at android.view.View.getDisplayList(View.java:13404)
        at android.view.View.draw(View.java:14182)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at android.view.View.draw(View.java:14468)
        at androidx.appcompat.widget.ActionBarOverlayLayout.draw(:543)
        at android.view.View.getDisplayList(View.java:13362)
        at android.view.View.getDisplayList(View.java:13404)
        at android.view.View.draw(View.java:14182)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)

**Comment by ezefire** [comment]
Hi ! I have the same problem :

java.lang.NoClassDefFoundError: com.tistory.zladnrms.roundablelayout.RoundableLayout$getOutlineProvider$1
	at com.tistory.zladnrms.roundablelayout.RoundableLayout.getOutlineProvider(RoundableLayout.kt:262)
	at com.tistory.zladnrms.roundablelayout.RoundableLayout.dispatchDraw(RoundableLayout.kt:223)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.draw(View.java:14739)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14739)
	at android.widget.FrameLayout.draw(FrameLayout.java:534)
	at android.widget.ScrollView.draw(ScrollView.java:1614)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14739)
	at android.widget.FrameLayout.draw(FrameLayout.java:534)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2431)
	at android.view.View.draw(View.java:14739)
	at android.widget.FrameLayout.draw(FrameLayout.java:534)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2411)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1627)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1506)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2728)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2593)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2216)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5333)
	at java.lang.reflect.Method.invokeNative(Native Method)
